### ISSUE TITLE
View Logs to be changed to 'Consent history' 

### ISSUE THREAD

**Issue by kashishmalik** [decentralised-dataexchange/bb-consent-privacy-dashboard#10]
View Logs to be changed to 'Consent history'

**Comment by lalc** [comment]
Where is this change being proposed, if I may ask? 

And what is the thought process?

**Comment by kashishmalik** [comment]
In the web client privacy dashboard, it shows as View Logs but in the mobile privacy dashboard it shows Consent history.

<img width="229" alt="Screenshot 2023-11-21 at 22 44 01" src="https://github.com/decentralised-dataexchange/bb-consent-privacy-dashboard/assets/92527972/a1b8a3b1-624f-4f5f-bb72-3fdccdcb62a4">

**Comment by lalc** [comment]
@georgepadayatti Thoughts on this?

**Comment by georgepadayatti** [comment]
> @georgepadayatti Thoughts on this?

Agree to be consistent.
