### ISSUE TITLE
There shall be an option to view the full data agreement

### ISSUE THREAD

**Issue by lalc** [decentralised-dataexchange/bb-consent-privacy-dashboard#15]
It shall be the same screen used as a pop-up form left as in the consent record screen. 

**Example:**

<img width="479" alt="Screenshot 2024-01-09 at 12 20 43" src="https://github.com/decentralised-dataexchange/bb-consent-privacy-dashboard/assets/455274/898d8337-2f6e-4bbe-8f1a-0653e304935a">

**Comment by MARZOOQUE** [comment]
[Privacy_Dashboard_Wireframes.pdf](https://github.com/user-attachments/files/17161843/Privacy_Dashboard_Wireframes.pdf)
