### ISSUE TITLE
Show the values for Lawful basis of processing in read data agreement similar to the other attribute values

### ISSUE THREAD

**Issue by sreelakshmyunnikrishnan** [decentralised-dataexchange/bb-consent-privacy-dashboard#22]
![Screenshot from 2024-10-02 18-21-24](https://github.com/user-attachments/assets/a2153665-fed8-46c1-b086-8c3a4e961abf)

Reference:
[Privacy_Dashboard_Wireframes (1).pdf](https://github.com/user-attachments/files/17229724/Privacy_Dashboard_Wireframes.1.pdf)

**Comment by sreelakshmyunnikrishnan** [comment]
Tested in 2024.10.1 locally. @MARZOOQUE @kashishmalik please confirm the UI. 
![Image](https://github.com/user-attachments/assets/1513cc68-4be9-4682-9c92-cc94d47696ff)

**Comment by kashishmalik** [comment]
UI is correct
